### ISSUE TITLE
Ionic not working in demo

### ISSUE THREAD

**Issue by anismomin** [benorama/ngrx-demo-workspace#6]
website is working fine.
but getting this error on ionic serve. 

chunk {128} 128.js, 128.js.map () 7.29 kB  [rendered]

ERROR in ./src/global.scss (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/raw-loader!/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/postcss-loader/lib??embedded!/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/sass-loader/lib/loader.js??ref--15-3!./src/global.scss)
Module build failed: Error: Can't resolve '@ionic/angular/css/colors.css' in '/Users/anismemom/Code/net/ngrx-demo-workspace/apps/mobile/src'
    at doResolve (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/Resolver.js:180:19)
    at hook.callAsync (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn5 (eval at create (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:57:1)
    at resolver.doResolve (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/Users/anismemom/Code/net/ngrx-demo-workspace/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
ℹ ｢wdm｣: Failed to compile.

**Comment by benorama** [comment]
Indeed, this was link to some breaking change in latest Ionic 4 beta (https://github.com/ionic-team/ionic/issues/15423).
It should be solved now.
